### ISSUE TITLE
AttributeError: module 'google.cloud.datacatalog_v1beta1.types' has no attribute 'TagTemplate'

### ISSUE THREAD

**Issue by InLaw** [GoogleCloudPlatform/datacatalog-templates#1]
google-cloud-datacatalog = 2.0.0

```
python create_template.py $GOOGLE_APPLICATION_CREDENTIALS $PROJECT $REGION $TEMPLATE
Traceback (most recent call last):
  File "create_template.py", line 126, in <module>
    create_template(args.key_file, args.project_id, args.region, args.yaml_file)
  File "create_template.py", line 42, in create_template
    template_instance = types.TagTemplate()
AttributeError: module 'google.cloud.datacatalog_v1beta1.types' has no attribute 'TagTemplate'
```
----

Which version of google-cloud-datacatalog are you using?

**Comment by shirleycohen** [comment]
This is an old issue. The script has been tested on google-cloud-datacatalog==3.3.0
